<a href="https://colab.research.google.com/github/MohanPatil1/DS-And-DA-Assignments/blob/main/EDA_2_New.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data = pd.read_csv('iris.csv',index_col=0)

In [3]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [4]:
data1 = data.copy()

In [5]:
labelencoder = LabelEncoder()
data1.iloc[:,-1]=labelencoder.fit_transform(data1.iloc[:,-1])

In [6]:
data1

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1             5.1          3.5           1.4          0.2        0
2             4.9          3.0           1.4          0.2        0
3             4.7          3.2           1.3          0.2        0
4             4.6          3.1           1.5          0.2        0
5             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
146           6.7          3.0           5.2          2.3        2
147           6.3          2.5           5.0          1.9        2
148           6.5          3.0           5.2          2.0        2
149           6.2          3.4           5.4          2.3        2
150           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

# One Hot Encoder
- Using sklearn

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [8]:
data2 = pd.read_csv('iris.csv',index_col=0)

In [9]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
5             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [10]:
OHE =OneHotEncoder()

In [11]:
enc_df = pd.DataFrame(OHE.fit_transform(data2[['Species']]).toarray())

In [12]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [13]:
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
1             5.1          3.5           1.4          0.2  1.0  0.0  0.0
2             4.9          3.0           1.4          0.2  1.0  0.0  0.0
3             4.7          3.2           1.3          0.2  1.0  0.0  0.0
4             4.6          3.1           1.5          0.2  1.0  0.0  0.0
5             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
146           6.7          3.0           5.2          2.3  0.0  0.0  1.0
147           6.3          2.5           5.0          1.9  0.0  0.0  1.0
148           6.5          3.0           5.2          2.0  0.0  0.0  1.0
149           6.2          3.4           5.4          2.3  0.0  0.0  1.0
150           5.9          3.0           5.1          1.8  NaN  NaN  NaN

[150 rows x 7 columns]

# Using Pandas

In [14]:
import pandas as pd

In [15]:
data3 =pd.read_csv('iris.csv',index_col=0)

In [16]:
data_encoded=pd.get_dummies(data3)

In [17]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

# Isolation Forest

In [18]:
from sklearn.ensemble import IsolationForest
import pandas as pd

In [19]:
data = pd.read_csv('iris.csv',index_col=0)
data_encoded=pd.get_dummies(data)

In [20]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

In [21]:
data_encoded['Petal.Width'].describe(percentiles=[0.01,0.02,0.9,0.99,0.991,0.992])

count    150.000000
mean       1.199333
std        0.762238
min        0.100000
1%         0.100000
2%         0.100000
50%        1.300000
90%        2.200000
99%        2.500000
99.1%      2.500000
99.2%      2.500000
max        2.500000
Name: Petal.Width, dtype: float64

In [22]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

IsolationForest(contamination=0.01, random_state=10)

In [23]:
y_pred_outliers = clf.predict(data_encoded)

In [24]:
y_pred_outliers # -1 for outlier and 1 for inliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [25]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

In [26]:
data_encoded.loc[151]=[20,40,30,50,1,0,0] # Added Ourlier here

In [ ]:
data_encoded

In [28]:
# Training the model
clf =IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

IsolationForest(contamination=0.01, random_state=10)

In [29]:
y_pred_outliers=clf.predict(data_encoded)

In [30]:
y_pred_outliers # Last has -1 so its an recently added oulier

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1])

In [31]:
data_encoded['anomaly']=clf.predict(data_encoded.iloc[:,0:7])

In [32]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,anomaly
1,5.1,3.5,1.4,0.2,1,0,0,1
2,4.9,3.0,1.4,0.2,1,0,0,1
3,4.7,3.2,1.3,0.2,1,0,0,1
4,4.6,3.1,1.5,0.2,1,0,0,1
5,5.0,3.6,1.4,0.2,1,0,0,1
...,...,...,...,...,...,...,...,...
147,6.3,2.5,5.0,1.9,0,0,1,1
148,6.5,3.0,5.2,2.0,0,0,1,1
149,6.2,3.4,5.4,2.3,0,0,1,1
150,5.9,3.0,5.1,1.8,0,0,1,1
151,20.0,40.0,30.0,50.0,1,0,0,-1

In [33]:
# Print the Outlier data points
data_encoded[data_encoded['anomaly']==-1]

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica,anomaly
107,4.9,2.5,4.5,1.7,0,0,1,-1
151,20.0,40.0,30.0,50.0,1,0,0,-1

In [39]:
# Example of findout outlier in given list
import pandas as pd

In [35]:
df=pd.DataFrame({'Marks':[50,80,82,95,800],
                 'Time':[1,2,3,1.5,60]})
df

   Marks  Time
0     50   1.0
1     80   2.0
2     82   3.0
3     95   1.5
4    800  60.0

In [36]:
iso = IsolationForest(random_state=10,contamination=0.1)
iso.fit(df)
out=iso.predict(df)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

In [37]:
out # -1 outlier

array([ 1,  1,  1,  1, -1])

In [38]:
df['Score']=out
df

   Marks  Time  Score
0     50   1.0      1
1     80   2.0      1
2     82   3.0      1
3     95   1.5      1
4    800  60.0     -1

# PPS Score

In [40]:
# Install the Package
!pip install ppscore

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ppscore
  Downloading ppscore-1.3.0.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from ppscore) (1.4.4)
Requirement already satisfied: scikit-learn<2.0.0,>=0.20.2 in /usr/local/lib/python3.9/dist-packages (from ppscore) (1.2.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2022.7.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.1.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn<2.0.0,>=0.20.2->ppscore) (1.10.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.0.0->ppscore) (1.16.0)
Building wheels for collected packages: ppscore
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.3.0-py2.py3-none-any.whl size=13165 sha256=4575fdbffdea4869e889121dc72556044859a7c2bddef27b1f36c935c2c30b9a
  Stored in directory: /root/.cache/pip/wheels/d8/2d/fc/c1699298a1241684a460b125835f7871ee8e3ab3afea9b5d6f
Successfully built ppscore
Installing collected packages: ppscore
Successfully installed ppscore-1.3.0

In [41]:
import ppscore as pps

In [42]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [44]:
# pps.score(df,'feature_cols','target_cols')
pps.score(data,'Sepal.Length','Petal.Length')

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [45]:
# Calculate the whole PPS matrix
pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None

In [47]:
df=pd.DataFrame(pps.matrix(data))
df[df.case!='predict_itself'].iloc[:,[0,1,2,3,5,8]].sort_values('ppscore',ascending=False)

,x,y,ppscore,case,metric,model
19,Petal.Width,Species,0.927652,classification,weighted F1,DecisionTreeClassifier()
14,Petal.Length,Species,0.884812,classification,weighted F1,DecisionTreeClassifier()
17,Petal.Width,Petal.Length,0.798274,regression,mean absolute error,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,mean absolute error,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,mean absolute error,DecisionTreeRegressor()
13,Petal.Length,Petal.Width,0.744945,regression,mean absolute error,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,mean absolute error,DecisionTreeRegressor()
10,Petal.Length,Sepal.Length,0.525617,regression,mean absolute error,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,weighted F1,DecisionTreeClassifier()
3,Sepal.Length,Petal.Width,0.431739,regression,mean absolute error,DecisionTreeRegressor()
20,Species,Sepal.Length,0.409634,regression,mean absolute error,DecisionTreeRegressor()
15,Petal.Width,Sepal.Length,0.383911,regression,mean absolute error,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,mean absolute error,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,mean absolute error,DecisionTreeRegressor()
7,Sepal.Width,Petal.Length,0.172375,regression,mean absolute error,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,weighted F1,DecisionTreeClassifier()
8,Sepal.Width,Petal.Width,0.132858,regression,mean absolute error,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,mean absolute error,DecisionTreeRegressor()
5,Sepal.Width,Sepal.Length,0.006966,regression,mean absolute error,DecisionTreeRegressor()
1,Sepal.Length,Sepal.Width,0.000000,regression,mean absolute error,DecisionTreeRegressor()