<a href="https://colab.research.google.com/github/MohanPatil1/DS-And-DA-Assignments/blob/main/EDA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Label Encoder

In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
data = pd.read_csv('iris.csv',index_col=0)

In [3]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa

In [4]:
data1 = data.copy()

In [5]:
labelencoder = LabelEncoder()
data1.iloc[:,-1]=labelencoder.fit_transform(data1.iloc[:,-1])

In [7]:
data1

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
1             5.1          3.5           1.4          0.2        0
2             4.9          3.0           1.4          0.2        0
3             4.7          3.2           1.3          0.2        0
4             4.6          3.1           1.5          0.2        0
5             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
146           6.7          3.0           5.2          2.3        2
147           6.3          2.5           5.0          1.9        2
148           6.5          3.0           5.2          2.0        2
149           6.2          3.4           5.4          2.3        2
150           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

# One Hot Encoder
- Using sklearn

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
data2 = pd.read_csv('iris.csv',index_col=0)

In [10]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
5             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [11]:
OHE =OneHotEncoder()

In [13]:
enc_df = pd.DataFrame(OHE.fit_transform(data2[['Species']]).toarray())

In [14]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [15]:
data_final = data2.iloc[:,0:4].join(enc_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
1             5.1          3.5           1.4          0.2  1.0  0.0  0.0
2             4.9          3.0           1.4          0.2  1.0  0.0  0.0
3             4.7          3.2           1.3          0.2  1.0  0.0  0.0
4             4.6          3.1           1.5          0.2  1.0  0.0  0.0
5             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
146           6.7          3.0           5.2          2.3  0.0  0.0  1.0
147           6.3          2.5           5.0          1.9  0.0  0.0  1.0
148           6.5          3.0           5.2          2.0  0.0  0.0  1.0
149           6.2          3.4           5.4          2.3  0.0  0.0  1.0
150           5.9          3.0           5.1          1.8  NaN  NaN  NaN

[150 rows x 7 columns]

# Using Pandas

In [16]:
import pandas as pd

In [17]:
data3 =pd.read_csv('iris.csv',index_col=0)

In [18]:
data_encoded=pd.get_dummies(data3)

In [19]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

# Isolation Forest

In [20]:
from sklearn.ensemble import IsolationForest
import pandas as pd

In [21]:
data = pd.read_csv('iris.csv',index_col=0)
data_encoded=pd.get_dummies(data)

In [23]:
data_encoded

,Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species_setosa,Species_versicolor,Species_virginica
1,5.1,3.5,1.4,0.2,1,0,0
2,4.9,3.0,1.4,0.2,1,0,0
3,4.7,3.2,1.3,0.2,1,0,0
4,4.6,3.1,1.5,0.2,1,0,0
5,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
146,6.7,3.0,5.2,2.3,0,0,1
147,6.3,2.5,5.0,1.9,0,0,1
148,6.5,3.0,5.2,2.0,0,0,1
149,6.2,3.4,5.4,2.3,0,0,1
150,5.9,3.0,5.1,1.8,0,0,1

In [24]:
data_encoded['Petal.Width'].describe(percentiles=[0.01,0.02,0.9,0.99,0.991,0.992])

count    150.000000
mean       1.199333
std        0.762238
min        0.100000
1%         0.100000
2%         0.100000
50%        1.300000
90%        2.200000
99%        2.500000
99.1%      2.500000
99.2%      2.500000
max        2.500000
Name: Petal.Width, dtype: float64

In [25]:
# training the model
clf = IsolationForest(random_state=10,contamination=.01)
clf.fit(data_encoded)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(

IsolationForest(contamination=0.01, random_state=10)

In [26]:
y_pred_outliers = clf.predict(data_encoded)

In [27]:
y_pred_outliers # -1 for outlier and 1 for inliers

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])